// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP3ZXqWb_d3vWkY7y5Ge6LVj9v4oELnCo',
    appId: '1:402931950541:web:6d6b28dd359be0fa4a5a84',
    messagingSenderId: '402931950541',
    projectId: 'auth-second-try',
    authDomain: 'auth-second-try.firebaseapp.com',
    storageBucket: 'auth-second-try.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsmamet96Z7mr6oXxgyIPiuwyLUnimdwc',
    appId: '1:402931950541:android:44ea7138394c8c1c4a5a84',
    messagingSenderId: '402931950541',
    projectId: 'auth-second-try',
    storageBucket: 'auth-second-try.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7adfvAVZu77cgpNRtQiHg_4hRQuK32k',
    appId: '1:402931950541:ios:5b49e5731f6209294a5a84',
    messagingSenderId: '402931950541',
    projectId: 'auth-second-try',
    storageBucket: 'auth-second-try.appspot.com',
    iosClientId: '402931950541-rnd5f2o85g6mjl5qk7db6h5v778u4ark.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationThirdTrial',
  );
}
